CREATE TABLE sessions (
	id SERIAL PRIMARY KEY,
	host VARCHAR(255) NOT NULL,
	port INT NOT NULL,
	session_id VARCHAR(255) NOT NULL,
	protocol VARCHAR(64) NOT NULL,
	title VARCHAR(255) NOT NULL,
	users INT NOT NULL,
	usernames VARCHAR(512) NOT NULL,
	password BOOLEAN NOT NULL,
	nsfm BOOLEAN NOT NULL,
	owner VARCHAR(128) NOT NULL,
	started TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_active TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	unlisted BOOLEAN NOT NULL DEFAULT FALSE,
	update_key VARCHAR(255) NOT NULL,
	client_ip VARCHAR(64) NOT NULL,
	roomcode VARCHAR(16) DEFAULT NULL CONSTRAINT unique_roomcode UNIQUE,
	private BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE hostbans (
	host VARCHAR(255) NOT NULL PRIMARY KEY,
	expires TIMESTAMP WITH TIME ZONE,
	notes VARCHAR(512) NOT NULL DEFAULT ''
);

